version: "3.5"

services:
  nginx:
    ports:
      - 443:443
    volumes:
      - ./nginx/certbot/conf:/etc/nginx/ssl:ro
      - ./nginx/nginx-ssl.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      SSL_CERTIFICATE_NAME: ${SSL_CERTIFICATE_NAME:-fullchain}
      SSL_KEY_NAME: ${SSL_KEY_NAME:-privkey}
