version: "3.5"

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    networks:
      - default
    ports:
      - 80:80
    volumes:
      - ./nginx/locations:/etc/nginx/templates/locations:ro
      - ./nginx/errors:/app/errors:ro
      - ./nginx/utils:/etc/nginx/templates/utils:ro
      - ./nginx/nginx.template:/etc/nginx/templates/default.conf.template:ro
    healthcheck:
      test: service nginx status || exit 1
      interval: 10s
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CERTBOT_MOUNT: "#"
      # -- Do not serve apps by default --
      # Let dedicated docker-compose.app.yml files edit this value so that services are served properly
      # This allows to comment "includes" in nginx conf file (cf nginx/utils/nginx.apps_locations.template)
      # if value is "#", the app location file will not be included in nginx conf
      # if value is "", th app location file will be included in nginx conf
      FORMS_MOUNT: "#"
      PORTAL_MOUNT: "#"
      MAPS_MOUNT: "#"
      NEWS_MOUNT: "#"
      PERFOS_MOUNT: "#"

  redis:
    image: registry.asap.dsna.fr/infogenestatique/diapason/docker/redis:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s

networks:
  default:
    external: true
    name: public
