# Generated by Django 3.2.9 on 2021-11-14 18:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Intitulé')),
                ('file', models.FileField(max_length=251, upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fichier PDF')),
                ('color', models.CharField(blank=True, max_length=10, null=True, verbose_name='Couleur de fond')),
                ('textColor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Couleur du texte')),
                ('icon', models.FileField(blank=True, help_text='Fichier SVG de préférence', max_length=250, upload_to='icons', verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Fichier',
                'verbose_name_plural': 'Fichiers',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Numéro de page')),
                ('content_index', models.TextField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='filetree.staticfile')),
            ],
        ),
    ]
