# Generated by Django 3.2.9 on 2021-11-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nav', '0002_auto_20211114_1919'),
        ('filetree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='nav.tabletappconfig')),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='filetree.staticfile')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, help_text='Lien à utiliser pour accéder à ce profil (ex : mon-profil)', max_length=20, null=True, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=50, verbose_name='Titre')),
                ('dark_theme', models.BooleanField(default=False, verbose_name='Thème sombre')),
                ('show_photo_button', models.BooleanField(default=False, verbose_name='Bouton Appareil Photo')),
                ('show_search_field', models.BooleanField(default=False, verbose_name='Champ de recherche')),
                ('emergency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.layoutelement', verbose_name="En cas d'urgence")),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='ProfileMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, help_text="'*' pour indiquer un profil par défaut globalement.", max_length=20, null=True, verbose_name='Adresse IP')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings', to='profiles.profile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Mapping Profil-IP',
            },
        ),
        migrations.CreateModel(
            name='LayoutCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(default=0, verbose_name='Rangée')),
                ('col', models.PositiveIntegerField(default=0, verbose_name='Colonne')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='profiles.layoutelement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Disposition',
                'ordering': ['row', 'col'],
                'unique_together': {('row', 'col', 'profile')},
            },
        ),
    ]
