# Generated by Django 3.2.9 on 2021-11-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filetree', '0002_folder'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutelement',
            name='folder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='filetree.folder'),
        ),
        migrations.AlterField(
            model_name='layoutcell',
            name='element',
            field=models.ForeignKey(limit_choices_to=models.Q(('folder__isnull', True), ('folder__tn_parent__isnull', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='profiles.layoutelement'),
        ),
    ]
