# Generated by Django 3.2.9 on 2021-11-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('profiles', '0002_auto_20211121_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_engines',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='search.SearchEngine'),
        ),
    ]
