# Generated by Django 3.2.9 on 2021-11-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_auto_20211114_1919'),
        ('search', '0001_initial'),
        ('profiles', '0003_profile_search_engines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emergency',
        ),
        migrations.AddField(
            model_name='profile',
            name='additional_apps',
            field=models.ManyToManyField(blank=True, help_text="Application non affichées sur la page d'accueil mais utilisables par le moteur de recherche", related_name='profiles_additional', to='nav.TabletAppConfig', verbose_name='Applications supplémentaires'),
        ),
        migrations.AddField(
            model_name='profile',
            name='toolbar',
            field=models.ManyToManyField(blank=True, help_text='Applications affichées sur toutes les pages du profil', related_name='toolbars', to='profiles.LayoutElement', verbose_name="Applications en barre d'outils"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='search_engines',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='search.SearchEngine', verbose_name='Moteurs de recherche'),
        ),
    ]
