# Generated by Django 3.2.9 on 2021-11-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20211128_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dark_theme',
            field=models.BooleanField(default=True, verbose_name='Thème sombre'),
        ),
    ]
