# Generated by Django 3.2.10 on 2022-01-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_dark_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_profile_switch',
            field=models.BooleanField(default=True, verbose_name='Sélecteur de profil'),
        ),
    ]
