# Generated by Django 3.2.10 on 2022-01-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_show_profile_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_external_indicators',
            field=models.BooleanField(default=False, verbose_name='Indicateurs de liens externes'),
        ),
    ]
