# Generated by Django 3.2.13 on 2022-06-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_show_external_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_message',
            field=models.CharField(blank=True, help_text="Message d'information affiché sur le profil",
                                   max_length=100, null=True, verbose_name="Message de l'administrateur"),
        ),
    ]
