# Generated by Django 3.2.13 on 2022-07-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('DIAPASON', 'Diapason'), ('MEDIAWIKI', 'Mediawiki')], max_length=25, verbose_name="Type d'API")),
                ('template_url', models.CharField(help_text="{root_url} sera remplacé par l'url de l'application. {search_query} sera remplacé par la recherche de l'utilisateur", max_length=255, verbose_name="Modèle d'URL")),
                ('search_engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to='search.searchengine')),
            ],
            options={
                'verbose_name': 'Accès par API',
                'verbose_name_plural': 'Accès par API',
            },
        ),
    ]
