# Generated by Django 3.2.13 on 2022-07-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchapiendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchapiendpoint',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Libellé'),
        ),
    ]
