# Generated by Django 3.2.9 on 2021-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssoconfig',
            name='client_uuid',
            field=models.TextField(blank=True),
        ),
    ]
