# Generated by Django 3.2.9 on 2021-11-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_ssoconfig_client_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssouserprofile',
            name='userinfo',
        ),
    ]
