# Generated by Django 3.2.13 on 2022-06-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0003_remove_ssouserprofile_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssoconfig',
            name='_certs',
        ),
        migrations.RemoveField(
            model_name='ssoconfig',
            name='client_uuid',
        ),
    ]
