version: "3.5"

services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    volumes:
      - ./nginx/certbot/www:/var/www/certbot:ro
    environment:
      CERTBOT_MOUNT: ""
