# Generated by Django 3.2.9 on 2021-11-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_portal', models.BooleanField(default=True, verbose_name='Afficher sur le portail')),
                ('rank', models.PositiveIntegerField(default=0, help_text='Rang de cette app dans sa catégorie', verbose_name='Ordre')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('screencap', models.ImageField(blank=True, max_length=250, upload_to='screencaps', verbose_name="Capture d'écran")),
                ('extra', models.TextField(blank=True, null=True, verbose_name='Contenu extra')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nav.appcategory', verbose_name='Catégorie')),
            ],
            options={
                'ordering': ['category', 'rank', 'parent_app__title'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tabletgriditem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tabletgriditem',
            name='app',
        ),
        migrations.RemoveField(
            model_name='tabletgriditem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='tabletprofilemapping',
            name='profile',
        ),
        migrations.AlterModelOptions(
            name='appitem',
            options={'ordering': ['portal_config__category', 'portal_config__rank', 'title'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.DeleteModel(
            name='DesktopAppConfig',
        ),
        migrations.DeleteModel(
            name='TabletGridItem',
        ),
        migrations.DeleteModel(
            name='TabletProfile',
        ),
        migrations.DeleteModel(
            name='TabletProfileMapping',
        ),
        migrations.AddField(
            model_name='portalappconfig',
            name='parent_app',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_config', to='nav.appitem'),
        ),
    ]
