# Generated by Django 3.2.10 on 2022-04-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_auto_20211114_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalappconfig',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portalappconfig',
            name='parent_app',
        ),
        migrations.AlterModelOptions(
            name='appitem',
            options={'ordering': ['title'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.DeleteModel(
            name='AppCategory',
        ),
        migrations.DeleteModel(
            name='PortalAppConfig',
        ),
    ]
